### PR TITLE
chore: add `retry(5)` to the Jenkinsfile

### PR DESCRIPTION
**Pull request by lemeurherve**
I removed it in #1565, putting it back trying to get builds passing.

### CODE REVIEW

**Comment by zbynek** [comment]
LGTM, but why is the build failing?

**Comment by dduportal** [comment]
> LGTM, but why is the build failing?

Not sure why to be honest :| There have been error when the build fetches the plugin contents since months. There used to be HTTP/500 from the backend which has been fixed 2 months ago (OOM in the JVM).

Now we see TCP/TLS errors like the one described in https://github.com/jenkins-infra/plugin-site/pull/1575#issue-2053569162  but only in infra.ci.jenkins.io, not on ci.jenkins.io which is weird.

**Comment by dduportal** [comment]
> I removed it in #1565, putting it back trying to get builds passing.

Problem is that the initial `Build` stage fails, so infra.ci.jenkins.io never reaches the "Deploy" phase (which is retried 5 times), so the build fails without retrying alas.

**Comment by lemeurherve** [comment]
Superseded by https://github.com/jenkins-infra/plugin-site/pull/1575

**Comment by zbynek** [comment]
But... API failing for a single plugin should result in a single docs page missing, not in whole build failing.

**Comment by dduportal** [comment]
> But... API failing for a single plugin should result in a single docs page missing, not in whole build failing.

I wholeheartedly agree with you! But i have no idea how to do it with this toolchain (out of my depth here)

**Pull request closed without merging**
