### PR TITLE
Remove API version from footer

### PR DESCRIPTION
**Pull request by zbynek**

### CODE REVIEW

**Comment by zbynek** [comment]
@dduportal any clue why is the build failing? (not urgent! 🎄 )

**Comment by halkeye** [comment]
I don't have VPN on my desktop anymore so I'll check on laptop tomorrow but you should request VPN access. https://github.com/jenkins-infra/docker-openvpn

**Comment by halkeye** [comment]
[1193](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1193)
00:41:17  panic: Unable to upload file: Put "https://api.netlify.com/api/v1/deploys/65877d6b1eb607e162c8b30b/files/%2Fzscaler-iac-scan%2Findex.html": read plugins/plugin-site/public/zscaler-iac-scan/index.html: file already closed

[1194](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1194)
00:41:17  

[1195](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1195)
00:41:17  goroutine 29 [running]:

[1196](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1196)
00:41:17  main.deploy.func1()

[1197](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1197)
00:41:17  	/home/runner/work/netlify-golang-deploy/netlify-golang-deploy/main.go:342 +0xb8

[1198](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1198)
00:41:17  created by main.deploy

[1199](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1199)
00:41:17  	/home/runner/work/netlify-golang-deploy/netlify-golang-deploy/main.go:335 +0x633

[1200](https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/PR-1578/1/pipeline-console/?start-byte=1146759&selected-node=60#log-1200)
script returned exit code 2

**Comment by halkeye** [comment]
retry fixed it

**Pull request merged**
