### PR TITLE
ci: secrets not secret

### PR DESCRIPTION
**Pull request by halkeye**
its been way too long since i wrote jenkinsfile

jenkinslint says its good

### CODE REVIEW

**Review by lemeurherve — APPROVED** [review]
Thanks!

**Comment by zbynek** [comment]
@lemeurherve did the Algolia upload work?

**Comment by halkeye** [comment]
No. It's not secrets ()

@lemeurherve is using with credentials now. I can't remember if that works in declarative but I've already gone to bed

**Comment by lemeurherve** [comment]
> @lemeurherve did the Algolia upload work?

Main build in progress: https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/main/617/console

🤞

**Pull request merged**
