### PR TITLE
:zap: fixing layouts of the search-results, searchBox

### PR DESCRIPTION
**Pull request by Mahmoudgalalz**
As mentioned that it's not recommended to make the plugins less per row.
I just modified the box alignment to be centered and 
SearchBox to be centered with the Algolia Logo

in both layouts List and grid 

the implementation was just adding a new class `add-m` which will add a margin to the left as the other way to fix this issue will require reconstructing all the body content 

image
image
image

### CODE REVIEW

**Comment by Mahmoudgalalz** [comment]
This should close #1324

**Comment by Mahmoudgalalz** [comment]
should I ignore the package-lock, and yarn.lock

to fix the build stage?
as they give me errors about deprecated packages and I fixed them using `npm audit --fix`

**Comment by Harsh3341** [comment]
Have you tried to build it locally? Using `gatsby build`

I can see you made changes in the root directory of the project refer to [Contribution Guide](https://github.com/jenkins-infra/plugin-site/blob/master/CONTRIBUTING.md#contributing-guide) and move to plugins/plugin-site and run commands there

**Review by NotMyFault — CHANGES_REQUESTED** [review]
> this is not clear, and it's returning too many plugins

> I recommend changing the layout to hold 4 cards and be centered when the side tab disappears

This PR lacks a proper motivation and clear description, which issue it aims to address.
The current layout presents up to 24 plugins on a 1920x1080 display, 50 per page, leading to the need to scroll twice to reach the page bottom. That's a compact design by choice, to display as much information within one space as possible.
That's the rationale, too. Commonly, there are multiple matches for a search term, the searcher then needs to compare them at a glance, and not by scrolling the page up and down.
Your proposal flattens out the number of displayed plugins to 4.

Could you provide your rationale justifying why reducing the page information by over 80% is an appropriate step to go, please?
I don't believe making the current layout less dense is the right step to go.
We host over 2k plugins. Your proposal makes sense if we hosted ~100 plugins only, returning a few items within a search query, but this is not the case.

**Comment by Mahmoudgalalz** [comment]
Yeah, the issue was started to fix the layout, but 
@MarkEWaite mentioned that we don't need to do that

So I proposed to fix some issues related to positioning of the grids

And placing the searchBox to the center

**Comment by Mahmoudgalalz** [comment]
> Have you tried to build it locally? Using `gatsby build`
> 
> I can see you made changes in the root directory of the project refer to [Contribution Guide](https://github.com/jenkins-infra/plugin-site/blob/master/CONTRIBUTING.md#contributing-guide) and move to plugins/plugin-site and run commands there

I do not change anything in root, these are the package-lock file

I will build it, and see

**Comment by halkeye** [comment]
> as they give me errors about deprecated packages and I fixed them using `npm audit --fix`

don't do unrelated changes in a given pr, it makes it much harder to review.

this is a yarn based project, so running npm is not correct behavior, so now we have two lock files. Please revert yarn.lock and remove package-lock.json from this pr.

**Comment by Mahmoudgalalz** [comment]
> > as they give me errors about deprecated packages and I fixed them using `npm audit --fix`
> 
> don't do unrelated changes in a given pr, it makes it much harder to review.
> 
> this is a yarn based project, so running npm is not correct behavior, so now we have two lock files. Please revert yarn.lock and remove package-lock.json from this pr.

Sorry for that, I was raising an issue, and it relates to smth else, but we discussed it there, and we found that we should leave it, and just center the content 

that what I did

and now I will revert the yarn.lock and remove the package-lock file

Thanks, @halkeye

**Comment by NotMyFault** [comment]
> So I proposed to fix some issues related to positioning of the grids

> And placing the searchBox to the center

I see, your first screenshot on this PR doesn't match with the goal of the PR. Hence, my question for clarification. I would recommend removing it, if that's not going to change.

**Comment by Harsh3341** [comment]
That just shows the centering of the boxes it think its ok

**Comment by NotMyFault** [comment]
> That just shows the centering of the boxes it think its ok

You missed my point.

Screenshot 2023-04-08 at 21 22 44

The 1st image shows a different layout (undesired) compared to the second one (desired). If the PR does not intend to change the design matching the first screenshot, as claimed by the submitter, it doesn't belong here.

**Comment by Harsh3341** [comment]
got it

**Comment by Mahmoudgalalz** [comment]
> > That just shows the centering of the boxes it think its ok
> 
> You missed my point.
> 
> Screenshot 2023-04-08 at 21 22 44
> 
> The 1st image shows a different layout (undesired) compared to the second one (desired). If the PR does not intend to change the design matching the first screenshot, it doesn't belong here.

you missed smth, as recommended not to change the count of plugins, I did not change them 

I just centered the content and boxes both layouts 
in the List and grid
they weren't centered and the SearchBox wasn't too

**Comment by NotMyFault** [comment]
> you missed smth, as recommended not to change the count of plugins, I did not change them

> I just centered the content and boxes both layouts

Ah I got it. This was not clear to me, given the PR description only provides very few details about the motivation. It would probably be better to provide the target in text form too, alternatively to images only.

Thanks for the explanation!

**Comment by Mahmoudgalalz** [comment]
> > you missed smth, as recommended not to change the count of plugins, I did not change them
> 
> > I just centered the content and boxes both layouts
> 
> Ah I got it. This was not clear to me, given the PR description only provides very few details about the motivation. It would probably be better to provide the target in text form too, alternatively to images only.
> 
> Thanks for the explanation!

I Just edited it, Thanks @NotMyFault

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Pull request merged**
