### PR TITLE
Switch plugin page tabs to real urls

### LINKED ISSUE #885: Menu is broken when opening anchor links
Clicking "dependencies" on https://plugins.jenkins.io/matrix-auth/ changes the URL to https://plugins.jenkins.io/matrix-auth/#dependencies.

Opening a link to "https://plugins.jenkins.io/matrix-auth/#dependencies" takes you there directly, but the menu doesn't change accordingly:

> Screenshot 2021-12-06 at 14 55 17

### PR DESCRIPTION
**Pull request by halkeye**
fixes #885 

* Client side routing
* We are using try-files in nginx, so it should try index.html so should work

### CODE REVIEW

**Comment by halkeye** [comment]
Okay, it seems to work fine now \o/
http://next-cherries.surge.sh/scp/dependencies

**Review by timja — APPROVED** [review]

**Comment by zbynek** [comment]
@timja does the test URL shared by @halkeye work for you? I get the 404 error message which is later partially replaced with the right content 😞 
image
Also serving actual content with http status 404 is bad for SEO. Wouldn't it be better to actually generate 4 static html files for each plugin?

**Comment by halkeye** [comment]
rawr, okay, i'm going to temporarily revert this. https://github.com/jenkins-infra/public-charts/pull/28 should fix in on plugins.jenkins.io. 
The one on surge was working fine last night, but isn't working now.

**Comment by zbynek** [comment]
Thanks for the ⚡ fast response!

**Pull request merged**
