### PR TITLE
fix: update plugin card color on dark theme

### PR DESCRIPTION
**Pull request by nouralmulhem**
related issue: #1577 

## **Before:**

image

## **After:**

image

### CODE REVIEW

**Comment by zbynek** [comment]
Thanks! Definitely looks better in dark mode. 

This also changes the color in light mode, causing the "icons" (`.Plugin--IconContainer i`) to have too low contrast now. Since the background for those is the same in light/dark mode, they should also use the same foreground in both.

**Comment by nouralmulhem** [comment]
thank you for noticing this!! , I think this has nothing to do with the fact that the text color has to change, wanted also to refer to which was presented previously

image

as you said i recommend making **`icon text foreground color`** unified (not the whole text), and this should be the solution, as the background color doesn't change

i will update my branch with the proposed solution and maybe you can share your thoughts again with me

**Review by zbynek — APPROVED** [review]
thanks!

**Comment by nouralmulhem** [comment]
@zbynek I'm kind of new, should I close and merge?

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Pull request merged**
