### PR TITLE
corrected space between top bar and heading

### LINKED ISSUE #1218: Insufficient space between top bar and heading in new layout
Submitted by @daniel-beck  as https://github.com/jenkins-infra/jenkins.io/issues/5330

Needs more padding between the top bar and the text

### PR DESCRIPTION
**Pull request by reveurguy**
Signed-off-by: reveurguy <59417546+reveurguy@users.noreply.github.com>
Fixes #1218

### CODE REVIEW

**Comment by halkeye** [comment]
Is there a better way to handle this longer term? a standard container jenkins.io uses or something that we could move towards?

**Comment by zbynek** [comment]
Thanks for checking, but I think this should be fixed in the jenkins.io repository, see https://github.com/jenkins-infra/jenkins.io/issues/5330 (@halkeye feel free to reopen if you disagree).

**Comment by halkeye** [comment]
> (@halkeye feel free to reopen if you disagree).

nope, that was more or less what I was looking into. I know the #grid-box is something specific to plugin site, and was thinking if we could switch to a generic container it would be healthier long term

**Comment by reveurguy** [comment]
currently i think this is the best solution, as the plugin site is maintained differently , we will have to make changes in this repo. I tried correcting this in the jenkins.io repo but it couldn't be changed from there

**Comment by reveurguy** [comment]
> Thanks for checking, but I think this should be fixed in the jenkins.io repository, see [jenkins-infra/jenkins.io#5330](https://github.com/jenkins-infra/jenkins.io/issues/5330) (@halkeye feel free to reopen if you disagree).

ok yeah i'll do that

**Comment by reveurguy** [comment]
should i add the changes in the current PR on the jenkins.io repo, which is: corrected fonts, made improvement to event section #5332 or wait for it to be merged to make the change?

**Comment by reveurguy** [comment]
i have made the changes and have committed them on the mentioned PR

**Pull request closed without merging**
