### PR TITLE
Centering Pagination Component for Whitespace Management

### PR DESCRIPTION
**Pull request by MondalSayantan**
- Pagination component left-justified in mobile devices was giving a **cluttered look** and was resulting in **space wastage.**
- Added CSS class to center pagination component in mobile devices.
- Does not affect larger screen sizes

image

### CODE REVIEW

**Comment by MondalSayantan** [comment]
I think the benefit of centering this component would be more visible if #1276 is merged

**Comment by krisstern** [comment]
I do agree it looks good for the mobile version of the site, but the UI is kind of inconsistent with this new addition though.

**Comment by MondalSayantan** [comment]
> I do agree it looks good for the mobile version of the site, but the UI is kind of inconsistent with this new addition though.

Hello @krisstern 

I agree the UI gets inconsistent if we switch to a device with a different breakpoint. I have centered the component across every breakpoints with my latest commit. It looks much better and is a better management of whitespaces. Although a separate PR might be required to center the search box and the views tab. What do you think?

**Comment by zbynek** [comment]
@krisstern are you happy with the current state?

**Comment by krisstern** [comment]
Yes, this looks a lot better!

**Comment by krisstern** [comment]
@MondalSayantan You may want to pull in the latest changes from the `master` branch to your feature branch and work out any merge conflicts if any before this pull request can be approvoed and merged.

**Comment by krisstern** [comment]
Thanks @MondalSayantan for the code contribution!

**Pull request merged**
