### PR TITLE
Fix #885 - Properly handle tabs on page rehydrate

### LINKED ISSUE #885: Menu is broken when opening anchor links
Clicking "dependencies" on https://plugins.jenkins.io/matrix-auth/ changes the URL to https://plugins.jenkins.io/matrix-auth/#dependencies.

Opening a link to "https://plugins.jenkins.io/matrix-auth/#dependencies" takes you there directly, but the menu doesn't change accordingly:

> Screenshot 2021-12-06 at 14 55 17

### PR DESCRIPTION
**Pull request by halkeye**
fixes #885 

Test url - https://pensive-galileo-3fa514.netlify.app/scp/#dependencies

### CODE REVIEW

**Comment by zbynek** [comment]
The highlighting of the tabs/pills seems wrong: in your link "documentation" is highlighted, when you click "releases" you get two selected tabs...

I like this more than https://github.com/jenkins-infra/plugin-site/pull/890 since hashes are imho better fit for client side navigation 👍

**Comment by halkeye** [comment]
> I like this more than #890 since hashes are imho better fit for client side navigation 👍

yea but hashes are page anchors. These are not page anchors. So kinda using a system for a different purpose.

looking into the buttons, its hard to test because dev mode is client side only routing.

**Comment by halkeye** [comment]
so none of the javascript fires until you click on something (like the other tabs).

**Comment by halkeye** [comment]
image

hrmmmmmmm, the tab isn't rendering properly, yets being run and setup properly.

**Comment by halkeye** [comment]
okay, not totally psyched about the solution, but https://pensive-galileo-3fa514.netlify.app/scp/#dependencies is now client side only, and seems to work right.

**Comment by MarkEWaite** [comment]
> okay, not totally psyched about the solution, but https://pensive-galileo-3fa514.netlify.app/scp/#dependencies is now client side only, and seems to work right.

When I use that site and try to hover over one of the headings in the documentation tab, the hyperlink moves away from me.  For example, I hover over the "Change Log" heading and see a clickable link hovering on the "Version 1.9" below.  If I move to the icon to the right of "Version 1.9", the clickable link disappears while the link is still visible on the "Version 1.8" below it.

**Comment by halkeye** [comment]
Is that something I introduced by this change? What browser? got a video or anything (screentogif is awesome)

**Comment by halkeye** [comment]
I'm def seeing it on ie11, but I don't think its new for this change?

https://app.saucelabs.com/tests/4a03e344d8134ffb8bc9e052cbed6b14#1

**Comment by halkeye** [comment]
yea confirmed, same issue on ie11 on plugins.jenkins.io, so don't think introduced here.

**Comment by MarkEWaite** [comment]
> yea confirmed, same issue on ie11 on plugins.jenkins.io, so don't think introduced here.

I hadn't noticed it before, but I confirm that https://plugins.jenkins.io/scp/ shows the same "chase the link" behavior on Google Chrome.  Behavior is not from this change.

**Comment by timja** [comment]
It was reported in docs gitter today: https://gitter.im/jenkinsci/docs?at=61b0bf1f76e379175528af62

**Comment by MarkEWaite** [comment]
> It was reported in docs gitter today: https://gitter.im/jenkinsci/docs?at=61b0bf1f76e379175528af62

I think that's reporting a different condition.  On the page https://plugins.jenkins.io/docker-workflow/#plugin-content-changelog I can hover over the heading "Demo" and see the link icon appear on the right.  When I move to the right, I can click the icon and it updates the browser URL with that id (as in https://plugins.jenkins.io/docker-workflow/#plugin-content-demo )

When I hover over "Change Log" on the page https://plugins.jenkins.io/scp/ , the link appears to the right of the text.  When I move to the right in order to click the link, the link disappears.

**Comment by timja** [comment]
Pretty sure it's the same root cause

**Comment by halkeye** [comment]
the hovering over elements is css, the h1 is a weird bounding box I couldn't figure out, the SVG shows up on h1:hover type thing.

The linking to wrong section things? We are partially using github HTML, and partially using our own, so the ids don't match, that'll have to be a different pr to link them up.

**Comment by halkeye** [comment]
> Pretty sure it's the same root cause

that being said, if you know what the cause is, please let me know

**Review by timja — APPROVED** [review]

**Comment by halkeye** [comment]
okay, https://github.com/jenkins-infra/jenkins.io/pull/4758 is the fix for the other issue.

Merging this one!

**Pull request merged**
