### PR TITLE
Display score resolution help when available

### PR DESCRIPTION
**Pull request by alecharp**
This is using https://github.com/jenkins-infra/plugin-health-scoring/pull/452

The idea is to provide a guide on how to improve a specific score category. This can help maintainers but could also help contributors into providing the fix to the plugin repository.

<details>
<summary>Screenshot:</summary>

Screenshot 2024-02-20 at 18 43 27

</details>

Not all categories have guidance on how to solve them.

### CODE REVIEW

**Comment by alecharp** [comment]
Build is failing because the field `resolutions` is not yet available in the response from `plugin-health.jenkins.io/api/scores`.

**Comment by lemeurherve** [comment]
> Build is failing because the field `resolutions` is not yet available in the response from `plugin-health.jenkins.io/api/scores`.

Version 3.5.0 deployed, restarted a build.

**Comment by alecharp** [comment]
thank you @lemeurherve !

**Comment by lemeurherve** [comment]
> Cannot query field "resolutions" on type "JenkinsPluginHealthScoreDetailsComponents".

**Comment by alecharp** [comment]
Yes, most probably because the scorings haven't been executed yet.
I can see the field in https://plugin-health.jenkins.io/api/scores, but it's `null`. Is there a way to mark it as "optional" in the GraphQL query? (I couldn't find if it was possible on the documentation)

**Comment by alecharp** [comment]
I can see that the `resolutions` field on the API is now correctly an array. The build should pass now.

**Review by NotMyFault — APPROVED** [review]

**Comment by alecharp** [comment]
Before we merge. Should plugin health scoring provide a map of `text <> link` so that the rendering here is less raw?

**Comment by alecharp** [comment]
I'd like to change the format of the resolutions so that the text can be more meaningful to readers.

**Comment by alecharp** [comment]
I have updated the screenshot in the pull request description. We can see that the resolutions links can have text now.

**Pull request merged**
