### PR TITLE
[FIX WEBSITE-220] - Add pretty 404 page

### PR DESCRIPTION
**Pull request by michaelmccaskill**
Related to issue [WEBSITE-220]

Summary of this pull request: 

Adds a pretty 404 page.

404 page

### CODE REVIEW

**Comment by daniel-beck** [comment]
How does this look?

**Comment by michaelmccaskill** [comment]
I will add screenshots.

**Comment by daniel-beck** [comment]
Does that pretty page also include the shared header?

**Comment by michaelmccaskill** [comment]
It does. I updated the screenshot. I also removed the spinner from that page because when the shared header is present the spinner is hidden. I need to consult with Gus for a proper fix, and to be fair this was out of the scope of the original ticket anyway.

**Comment by daniel-beck** [comment]
:+1:

**Pull request merged**
