### PR TITLE
Preview site when PR

### PR DESCRIPTION
**Pull request by halkeye**
🤞🤞

### CODE REVIEW

**Review by timja — APPROVED** [review]
There anyway to not comment on every commit 👅 

Looks like:
https://github.com/jenkinsci/pipeline-github-plugin#listing-a-pull-requests-comments
+
https://github.com/jenkinsci/pipeline-github-plugin#editing-a-comment

**Comment by halkeye** [comment]
🤞

**Comment by halkeye** [comment]
Url looks good, https://deploy-preview-951--jenkins-plugin-site-pr.netlify.app/robots.txt is disallowing search engines.  so assumingthis edit thing works, I'll merge

**Comment by timja** [comment]
> Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods find java.lang.Object groovy.lang.Closure

**Comment by halkeye** [comment]
yea, docs say comments is "Iterable<IssueComment>" which should have find? but that error is saying its a generic object?

**Comment by halkeye** [comment]
yay it found the old comment and updated it.
Also learned that we are cronjobing every PR :(

**Review by timja — APPROVED** [review]

**Pull request merged**
