### PR TITLE
Update the plugins number

### PR DESCRIPTION
**Pull request by donhui**
Update the plugins number to 1800+.

Related to issue # 

Summary of this pull request:

### CODE REVIEW

**Review by timja — APPROVED** [review]
seems fine, could do 1800 but some may be deprecated
```
curl -s https:// updates.jenkins.io/current/update-center.actual.json | jq -r '.plugins | keys[]' | wc -l
    1820
```

**Comment by donhui** [comment]
ok, I've updated the number.

**Review by timja — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]
Bold of you to assume I'm not going to suspend 20+ plugins' distribution any time soon 😄

**Comment by halkeye** [comment]
LGTM

It might be worth upgrading it to use count with gatsby's graphql so we can have it like # rounded down or something

**Pull request merged**
