### PR TITLE
Upgrade gatsby v3

### PR DESCRIPTION
**Pull request by halkeye**
Fully upgraded to gatsby v3 - Test site: https://plugin-site-regud.ondigitalocean.app/

Notable items:
* had to fork react-paginate to make the module create an artifact that was happy with gatsby (only runtime use of window, use "this" instead of "self", etc)
* manifest file is now pulled from jenkins.io since the plugin generating it wasn't updated
* use the new gatsby-image-plugin which handles the progressive loading of images without the big ugly graphql statement

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by markjacksonfishing — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Spent about five minutes to click through  the screens locally. Looks good

**Comment by zbynek** [comment]
* the favicon fails to load with Mixed Content: The page at 'https://plugin-site-regud.ondigitalocean.app/subversion/' was loaded over HTTPS, but requested an insecure favicon 'http://www.jenkins.io/favicon.ico'. This request has been blocked; the content must be served over HTTPS. 
* the SVG images look pixelated -- see the warning icon in https://plugin-site-regud.ondigitalocean.app/subversion/ and don't use the right color, because they are no longer inlined. I guess you removed the SVG plugin because of Gatsby 3 compatibility but maybe we can wait until it's possible to use SVGs with Gatsby 3.

**Review by zbynek — CHANGES_REQUESTED** [review]
* the favicon fails to load with Mixed Content: The page at 'https://plugin-site-regud.ondigitalocean.app/subversion/' was loaded over HTTPS, but requested an insecure favicon 'http://www.jenkins.io/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
* the SVG images look pixelated -- see the warning icon in https://plugin-site-regud.ondigitalocean.app/subversion/ and don't use the right color, because they are no longer inlined. I guess you removed the SVG plugin because of Gatsby 3 compatibility but maybe we can wait until it's possible to use SVGs with Gatsby 3.

**Comment by halkeye** [comment]
>     * the favicon fails to load with Mixed Content: The page at 'https://plugin-site-regud.ondigitalocean.app/subversion/' was loaded over HTTPS, but requested an insecure favicon 'http://www.jenkins.io/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

yea I couldn't for the life of me figure out where that was coming from, the meta tags are all https.

> the SVG images look pixelated -- see the warning icon in https://plugin-site-regud.ondigitalocean.app/subversion/ and don't use the right color, because they are no longer inlined. I guess you removed the SVG plugin because of Gatsby 3 compatibility but maybe we can wait until it's possible to use SVGs with Gatsby 3.

I probably don't need to handle the svg smartly with the gatsby-image-plugin, svgs are already pretty simple

**Comment by halkeye** [comment]
> the favicon fails to load with Mixed Content: The page at 'https://plugin-site-regud.ondigitalocean.app/subversion/' was loaded over HTTPS, but requested an insecure favicon 'http://www.jenkins.io/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

AHA! FOUND IT! not my fault!

image


> the SVG images look pixelated -- see the warning icon in https://plugin-site-regud.ondigitalocean.app/subversion/ and don't use the right color, because they are no longer inlined. I guess you removed the SVG plugin because of Gatsby 3 compatibility but maybe we can wait until it's possible to use SVGs with Gatsby 3.

fixed

**Comment by halkeye** [comment]
okay tired of trying to fix the other one, surge is super easy - https://next-cherries.surge.sh/subversion/

**Comment by halkeye** [comment]
Merging. I can clean up any unfound issues that come up in future PRs

**Pull request merged**
